---

application:
  audience: ustawki-api
  client-origin-url: http://localhost

server:
  error:
    whitelabel:
      enabled: false
  port: 8080

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-u8fr0gklyxw1nab8.us.auth0.com/
  web:
    resources:
      add-mappings: false

...
